# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml

modLoader="javafml" 

loaderVersion="[31,)" 

issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] 


modId="skeletonmod" 

version="1.0" 

displayName="Skeleton Mod" 

updateJSONURL="http://myurl.me/" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="http://example.com/" #optional

logoFile="" #optional

# A text field displayed in the mod UI
credits="Vinny Yu" 
# A text field displayed in the mod UI
authors="Love, Penny and Amber" 

description = """
  Hello. This is a description. 
 """


# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.skeletonmod]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[31,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.skeletonmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
